version: '3'

services:
  web:
    image: nginx:1.14.1
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www:ro
    links:
      - php

  php:
    build: docker/php
    volumes:
      - ./app:/var/www/app
      - ./bin:/var/www/bin
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./src:/var/www/src
      - ./tests:/var/www/tests
      - ./vendor:/var/www/vendor
      - ./web:/var/www/web

  db:
    image: postgres:10.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 372d784b4dcfddc5c9a1a8e019a0e919
      POSTGRES_DB: ocotpod_test